version: '3.8'

services:
  nextjs:
    image: dnghkm/board-v4-front:latest
    container_name: board-v4-front
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - board-network

networks:
  board-network:
    external: true
