version: '3.8'

services:
  nextjs:
    build: .
    container_name: board-v4-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  board-network:
    external: true
